/**
 * ONE schema registry. Every `.../vN` object in the studio is described here, once.
 *
 * WHY. The repository already contains a dozen versioned shapes — `journey/v1`, `gate-result/v1`,
 * `actor/v1`, `policy-decision/v1`, `criteria/v1`, `capability-manifest/v1`, and more — and each is
 * validated by hand-written `if` statements next to whichever script happens to read it. Three
 * consequences, all observed in this codebase rather than imagined:
 *
 *   - `feature: "F-001,F-002"` looks plausible and is one invalid ID;
 *   - `routes` versus `rules` in a policy file is caught only when a tool executes;
 *   - a manifest can be generated by documentation and rejected by a validator, with neither side
 *     wrong, because there was no single statement of the shape for them to disagree with.
 *
 * The lesson this repository keeps re-learning is that prose is not checkable and a field is. This
 * file is that lesson applied to the shapes themselves: a schema stops being something each reader
 * remembers and becomes something one module states.
 *
 * DELIBERATELY NOT a general JSON-Schema engine. Zero dependencies is a security property this
 * plugin has already passed a review on, and a validator complex enough to need its own tests is a
 * validator that will grow its own bugs. This does exactly what the observed defects needed:
 * required fields, types, enumerations, and a stated version.
 */

/** field: [type, required, enum?] — `type` is 'string' | 'number' | 'boolean' | 'array' | 'object' */
const REGISTRY = {
  'actor/v1': {
    fields: {
      actor_id: ['string', true],
      role: ['string', true],
      mode: ['string', true, ['insecure-local', 'attested']],
      session: ['string', false],
      model: ['string', false],
      delegator: ['string', false],
    },
    // What a reader must NEVER infer. Recorded here so the reason survives the next refactor.
    notes: 'mode is enumerated on purpose: "asserted" and "proven" must stay distinguishable forever.',
  },
  'gate-result/v1': {
    fields: {
      gate: ['string', true],
      subject: ['object', true],
      evaluated_at: ['string', true],
      result: ['string', true, ['PASS', 'FAIL', 'CANNOT_EVALUATE']],
    },
    notes: 'subject is required: a verdict with no subject is a verdict about nothing in particular.',
  },
  'policy-decision/v1': {
    fields: {
      risk: ['string', false],
      model: ['string', false],
      required_approvals: ['array', true],
      required_evidence: ['array', true],
      decided_at: ['string', true],
      policy: ['string', true],
    },
    notes: 'required_approvals is required even when empty — absent and "none needed" are different facts.',
  },
  'criteria/v1': {
    fields: { criteria: ['array', true] },
  },
  'journey/v1': {
    fields: { id: ['string', true], steps: ['array', true] },
  },
  'journey-result/v1': {
    fields: {
      journey_id: ['string', true],
      result: ['string', true, ['PASS', 'FAIL', 'CANNOT_EVALUATE']],
    },
    notes: 'journey_id is required: without it one cached report clears every declared journey.',
  },
  'project-profile/v1': {
    fields: { project_id: ['string', true], platforms: ['array', true], toolchain: ['object', true] },
  },
  'capability-manifest/v1': {
    fields: { root: ['string', true], roles: ['array', true] },
    notes: 'root is required — an inferred base silently changed what an agent was allowed to write.',
  },
  'readiness/v1': {
    fields: {
      candidate: ['object', true],
      gates: ['array', true],
      verdict: ['string', true, ['PASS', 'BLOCKED', 'CANNOT_EVALUATE', 'NOT_APPLICABLE', 'STALE']],
    },
    notes: 'STALE is in the enum deliberately: it is neither PASS nor BLOCKED and must never collapse into either.',
  },
};

function typeOf(value) {
  if (Array.isArray(value)) return 'array';
  if (value === null) return 'null';
  return typeof value;
}

/**
 * Validate an object against its declared schema.
 *
 * The object states its own schema in a `schema` key. An object that does not is not validated
 * against a guess — it is a stated error, because guessing which shape someone meant is how
 * `routes` passed for `rules`.
 */
function validate(value, expected) {
  const problems = [];
  if (typeOf(value) !== 'object') return { ok: false, problems: [`expected an object, got ${typeOf(value)}`] };

  const declared = value.schema;
  if (!declared) problems.push('no "schema" key — the shape must state what it is, never leave a reader to infer it');
  else if (expected && declared !== expected) problems.push(`schema is ${JSON.stringify(declared)}, expected ${JSON.stringify(expected)}`);

  const spec = REGISTRY[declared || expected];
  if (!spec) {
    return {
      ok: false,
      problems: [...problems, `${JSON.stringify(declared || expected)} is not in the schema registry — add it to scripts/lib/schemas.mjs before shipping a reader for it`],
    };
  }

  for (const [name, [type, required, allowed]] of Object.entries(spec.fields)) {
    const present = value[name] !== undefined && value[name] !== null;
    if (!present) {
      if (required) problems.push(`missing required field "${name}" (${type})`);
      continue;
    }
    if (typeOf(value[name]) !== type) {
      problems.push(`"${name}" must be ${type}, got ${typeOf(value[name])}`);
      continue;
    }
    if (allowed && !allowed.includes(value[name])) {
      problems.push(`"${name}" must be one of ${allowed.join(' | ')}, got ${JSON.stringify(value[name])}`);
    }
  }
  return { ok: problems.length === 0, problems, notes: spec.notes || '' };
}

/** Every schema this studio knows about. Used by the registry check to prove none is orphaned. */
function known() { return Object.keys(REGISTRY); }

export { validate, known, REGISTRY };
