name: ios

on: [push]

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: xcodebuild test -scheme SplitEven
